### ISSUE TITLE
Deploying in Heroku

### ISSUE THREAD

**Issue by adantoscano** [SnowStormIO/botkit-witai#3]
Hi!

I get an error when I deploy it in Heroku

> 2017-02-24T11:06:56.632334+00:00 app[web.1]: /app/node_modules/botkit-witai/src/botkit-witai.js:1
2017-02-24T11:06:56.632351+00:00 app[web.1]: (function (exports, require, module, __filename, __dirname) { const {Wit, log} = require('node-wit');
2017-02-24T11:06:56.632352+00:00 app[web.1]:                                                                     ^
2017-02-24T11:06:56.632353+00:00 app[web.1]: 
2017-02-24T11:06:56.632353+00:00 app[web.1]: SyntaxError: Unexpected token {
2017-02-24T11:06:56.632354+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2017-02-24T11:06:56.632354+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2017-02-24T11:06:56.632355+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2017-02-24T11:06:56.632355+00:00 app[web.1]:     at Module.load (module.js:357:32)
2017-02-24T11:06:56.632356+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2017-02-24T11:06:56.632356+00:00 app[web.1]:     at Module.require (module.js:367:17)
2017-02-24T11:06:56.632357+00:00 app[web.1]:     at require (internal/module.js:16:19)
2017-02-24T11:06:56.632357+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/botkit-witai/index.js:1:80)
2017-02-24T11:06:56.632358+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2017-02-24T11:06:56.632359+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)

I can't find where the problem is.

**Comment by RafaelCasuso** [comment]
That is probably because you're using an old NodeJS version. Do you know the NodeJS engine version you're using in your app?

**Comment by adantoscano** [comment]
5.10.1 is too old?

**Comment by RafaelCasuso** [comment]
If you can use 6+ it will work. But since there is no extensive use of 6+ capabilities I will probably downgrade such use to make it compatible with older versions. Right now the solution is using 6+.

**Comment by adantoscano** [comment]
ok I changed it to 6.6.0 and now run. Thanks and sorry...

**Comment by RafaelCasuso** [comment]
Thank you for pointing out compatibility issue!
